apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-enricher
  labels:
    app: acme-enricher-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-enricher-app
  template:
    metadata:
      labels:
        app: acme-enricher-app
    spec:
      containers:
        - name: sidecar-http-dispatcher
          image: n0npax/sidecar_http_dispatcher:0.0.1
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Gi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /app/config
              readOnly: true
              name: sidecar-conf
          env:
            - name: SIDECAR_CONFIG
              value: /app/config/sidecar_config.yaml
            - name: SIDECAR_PORT
              value: "5000"
        - name: acme-properiatery-software
          image: nginx:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: sidecar-conf
          configMap:
            name: sidecar-conf
            items:
              - key: sidecar_config.yaml
                path: sidecar_config.yaml
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: acme-enricher
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: acme-enricher-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination-service-app
  labels:
    app: destination-service-app
spec:
  selector:
    matchLabels:
      app: destination-service-app
  replicas: 3
  template:
    metadata:
      labels:
        app: destination-service-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              readOnly: true
              name: index-html
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: index-html
          configMap:
            name: index-html
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: destination-service-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: destination-service-app
