apiVersion: apps/v1
kind: Deployment
metadata:
  name: acme-enricher
  labels:
    app: acme-enricher-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-enricher-app
  template:
    metadata:
      labels:
        app: acme-enricher-app
    spec:
      containers:
        - name: sidecar-http-dispatcher
          image: n0npax/sidecar_http_dispatcher:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /app/config
              readOnly: true
              name: sidecar-conf
          env:
            - name: SIDECAR_CONFIG
              value: /app/config/sidecar_config.yaml
            - name: SIDECAR_PORT
              value: "5000"
        - name: acme-properiatery-software
          image: nginx:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: sidecar-conf
          configMap:
            name: sidecar-conf
            items:
              - key: sidecar_config.yaml
                path: sidecar_config.yaml
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: acme-enricher
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: acme-enricher-app
