resources:
  - destination_app.yaml
  - enricher_app.yaml
configMapGenerator:
  - name: acme-nginx-conf
    files:
      - configMaps/acme-nginx.conf
  - name: destination-nginx-conf
    files:
      - configMaps/destination-nginx.conf
  - name: sidecar-conf
    files:
      - configMaps/sidecar_config.yaml
  - name: index-html
    files:
      - configMaps/index.html
