resources:
  - destination_app.yaml
  - enricher_app.yaml
configMapGenerator:
  - name: nginx-conf
    files:
      - configMaps/nginx.conf
  - name: sidecar-conf
    files:
      - configMaps/sidecar_config.yaml
  - name: index-html
    files:
      - configMaps/index.html
