rewrites:
  dev:
    patch:
      - key: Host1a
        val: development
      - key: dispatched
        val: true
    destination: http://example.com
  qa:
    patch:
      - key: Host1a
        val: qa
      - key: dispatched
        val: true
    destination: http://example.com
key: environment
destination: http://example.com/default
