apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: k6test
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: loadimpact/k6:latest
          name: k6side
          resources: {}
          args:
            - run
            - --out
            - influxdb=http://influxdb.default.svc.cluster.local:8086/k6side
            - /app/k6/load.js
          volumeMounts:
            - mountPath: /app/k6
              readOnly: true
              name: k6script
          env:
            - name: ENDPOINT
              value: http://acme-enricher.default.svc.cluster.local/
        - image: loadimpact/k6:latest
          name: k6bare
          resources: {}
          args:
            - run
            - --out
            - influxdb=http://influxdb.default.svc.cluster.local:8086/k6bare
            - /app/k6/load.js
          volumeMounts:
            - mountPath: /app/k6
              readOnly: true
              name: k6script
          env:
            - name: ENDPOINT
              value: http://bare-acme-enricher.default.svc.cluster.local/
      volumes:
        - name: k6script
          configMap:
            name: k6script
            items:
              - key: k6script.js
                path: load.js
      restartPolicy: Never
status: {}
