---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bare-acme-enricher
  labels:
    app: bare-acme-enricher-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bare-acme-enricher-app
  template:
    metadata:
      labels:
        app: bare-acme-enricher-app
    spec:
      containers:
        - name: acme-properiatery-software
          image: nginx:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx
              readOnly: true
              name: nginx-conf
            - mountPath: /var/log/nginx
              name: log
      volumes:
        - name: nginx-conf
          configMap:
            name: bare-acme-nginx-conf
            items:
              - key: bare-acme-nginx.conf
                path: nginx.conf
        - name: sidecar-conf
          configMap:
            name: sidecar-conf
            items:
              - key: sidecar_config.yaml
                path: sidecar_config.yaml
        - name: log
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bare-acme-enricher
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bare-acme-enricher-app
