apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination-app
spec:
  template:
    spec:
      containers:
        - name: destination-app
          resources:
            limits:
              memory: 2Gi
              cpu: 2000m
