rewrites:
  dev:
    patch:
      - key: Host
        val: example.com
      - key: dispatched
        val: true
    destination: http://example.com
  qa:
    patch:
      - key: dispatched
        val: true
    destination: http://destination-service-app.default.svc.cluster.local
key: environment
destination: no_default
