name: CodeCov
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON: "3.8"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pip install poetry
          poetry env use system
          poetry install
          poetry run pytest -vs --cov-report=xml --cov=./ .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
