name: Docker Image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker image
        run: |
          USERNAME=n0npax
          VERSION=$(cat pyproject.toml | grep version | awk '{print $3}' | tr -d '"')
          docker build . --tag ${USERNAME}/sidecar_http_dispatcher:${VERSION}
          docker login --username ${USERNAME} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${USERNAME}/sidecar_http_dispatcher:${VERSION}
      - uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: "v1.10.1"
          kubernetes version: "v1.18.2"
      - name: Create k8s CI Cluster
        run: |
          set -x
          kubectl create cm nginx-conf --from-file example/configs/nginx.conf
          kubectl apply -f example/deployment.yaml
          ENDPOINT=$(minikube service acme-enricher --url=true)
          sleep 120
          kubectl wait --for=condition=available --timeout=120s deployment/acme-enricher
          curl -m 5 -v ${ENDPOINT} -H 'Host: example.com' -H 'environment1: qa'
