name: Docker Image

on:
  push:
    branches: [master]

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker image
        run: |
          USERNAME=n0npax
          VERSION=$(cat pyproject.toml | grep version | awk '{print $3}' | tr -d '"')
          docker build . --tag ${USERNAME}/sidecar_http_dispatcher:${VERSION}
          docker login --username ${USERNAME} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${USERNAME}/sidecar_http_dispatcher:${VERSION}
  run_e2e_tests:
    runs-on: ubuntu-latest
    needs: push_docker
    steps:
      - uses: actions/checkout@v2
      - uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: "v1.10.1"
          kubernetes version: "v1.18.2"
      - name: Run e2e in k8s CI Cluster
        run: |
          kubectl create cm nginx-conf --from-file example/configs/nginx.conf
          kubectl create cm sidecar-conf --from-file example/configs/sidecar_config.yaml
          kubectl apply -f example/deployment.yaml
          ENDPOINT=$(minikube service acme-enricher --url=true)
          sleep 90
          kubectl wait --for=condition=available --timeout=120s deployment/acme-enricher
          curl -m 5 -v ${ENDPOINT} -H 'environment: qa' --show-error --fail
