name: docker_release

on:
  push:
    branches: [master]

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker image
        run: |
          USERNAME=n0npax
          VERSION=$(cat .version)
          docker build . --tag ${USERNAME}/sidecar_http_dispatcher:${VERSION} --tag ${USERNAME}/sidecar_http_dispatcher:latest
          docker login --username ${USERNAME} -p ${{ secrets.DOCKER_TOKEN }}
          docker push ${USERNAME}/sidecar_http_dispatcher:${VERSION}
          docker push ${USERNAME}/sidecar_http_dispatcher:latest
