name: Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sidecar_http_dispatcher:$(cat pyproject.toml | grep version | awk '{print $3}' | tr -d '"')
