name: e2e

on: [push]

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: "v1.10.1"
          kubernetes version: "v1.18.2"
      - name: Run e2e in k8s CI Cluster
        run: |
          # build fresh image
          USERNAME=n0npax
          VERSION=$(cat pyproject.toml | grep version | awk '{print $3}' | tr -d '"')
          docker build . --tag ${USERNAME}/sidecar_http_dispatcher:${VERSION}

          # deploy system
          eval $(minikube docker-env) # use local docker images
          kubectl create cm nginx-conf --from-file example/configs/nginx.conf
          kubectl create cm sidecar-conf --from-file example/configs/sidecar_config.yaml
          kubectl create cm index-html --from-file example/configs/index.html
          kubectl apply -f example/deployment.yaml
          ENDPOINT=$(minikube service acme-enricher --url=true)

          # wait for system
          kubectl wait --for=condition=available --timeout=300s deployment/acme-enricher
          kubectl wait --for=condition=available --timeout=300s deployment/destination-service-app
          sleep 15
          kubectl get po

          # run basic e2e
          curl -m 5 -v ${ENDPOINT} -H 'environment: qa' --show-error --fail
      - name: k6 Load Test
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
          echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install k6 -y

          ENDPOINT=$(minikube service acme-enricher --url=true)
          k6 run k6/load.js -e ENDPOINT="${ENDPOINT}" --summary-export k6summary.json
      - name: Upload k6 summary
        uses: actions/upload-artifact@v1
        with:
          name: k6_summary
          path: ./k6summary.json
