name: Linters
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOLANG: "latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
